export const snackbarConstants = {
    ENQUEUE_SNACKBAR: 'ENQUEUE_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
    REMOVE_SNACKBAR: 'REMOVE_SNACKBAR'
}

export const authConstants = {
    USER_LOGIN: 'USER_LOGIN',
    USER_SIGNUP: 'USER_SIGNUP',
    USER_GOOGLE_SIGN_IN: 'USER_GOOGLE_SIGN_IN',
    USER_GOOGLE_SIGN_UP: 'USER_GOOGLE_SIGN_UP',
    AUTO_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    PASSWORD_RESET_EMAIL: 'PASSWORD_RESET_EMAIL',
    GET_LOGIN_INFO_DATA: 'GET_LOGIN_INFO_DATA'
}

export const userDataConstants = {
    GET_USER_DATA: 'GET_USER_DATA',
    GET_CUSTOM_USER_DATA: 'GET_CUSTOM_USER_DATA',
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    GET_ALL_USER_DATA: 'GET_ALL_USER_DATA',
    IMAGE_UPLOAD: 'IMAGE_UPLOAD',
    CHECK_PROFILE_COMPLETE_STEP_ONE: 'CHECK_PROFILE_COMPLETE_STEP_ONE',
    CHECK_PROFILE_COMPLETE_STEP_TWO: 'CHECK_PROFILE_COMPLETE_STEP_TWO'
}

export const libraryConstants = {
    ADD_BOOK: 'ADD_BOOK',
    GET_ALL_BOOK: 'GET_ALL_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
}